Upgrade to upcoming 4.0 release.
conda-forge/pymc-feedstock pull request #24
Opened 2021-10-19 08:12 UTC by twiecki

Preperation for the upcoming 4.0 release, do not merge yet.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2021-10-19 08:12 UTC, twiecki commented
@conda-forge-admin, please rerender

2021-12-16 09:42 UTC, twiecki commented
@conda-forge-admin, please rerender

2021-12-16 09:49 UTC, twiecki commented
@conda-forge-admin, please rerender

2021-12-16 10:10 UTC, michaelosthege requested changes

2021-12-16 10:10 UTC, michaelosthege commented on recipe/meta.yaml
> +    - pymc.glm
```suggestion
```

2021-12-16 10:11 UTC, michaelosthege commented on recipe/meta.yaml
> +    - cloudpicklel
```suggestion
    - cloudpickle
```

2021-12-16 10:16 UTC, twiecki commented
@conda-forge-admin, please rerender

2021-12-16 10:16 UTC, twiecki commented
@conda-forge-admin, please rerender

2021-12-16 10:36 UTC, twiecki commented
Alright, I think this looks good. CC @ocefpaf @fonnesbeck

2021-12-16 12:45 UTC, fonnesbeck approved these changes

2021-12-16 12:45 UTC, merged